# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 17:26
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_lms_activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityoccurrencestate',
            name='data',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='activitystate',
            name='data',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='userstate',
            name='data',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
