# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_lms_activities', '0002_auto_20160115_1726'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActivityOccurrenceState',
            new_name='ActivitySessionState',
        ),
    ]
