# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_lms_activities', '0003_auto_20160115_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitysessionstate',
            old_name='activity_slug',
            new_name='activity_key',
        ),
        migrations.RenameField(
            model_name='activitystate',
            old_name='activity_slug',
            new_name='activity_key',
        ),
        migrations.AlterUniqueTogether(
            name='activitysessionstate',
            unique_together=set([('user', 'activity_key', 'started')]),
        ),
        migrations.AlterUniqueTogether(
            name='activitystate',
            unique_together=set([('user', 'activity_key')]),
        ),
    ]
