# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_lms_activities', '0004_auto_20160206_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitystate',
            name='activity_class_path',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
