# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 20:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pinax_lms_activities", "0005_activitystate_activity_class_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userstate",
            name="user",
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="activitystate",
            name="user",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="activitysessionstate",
            name="activity_state",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name="sessions", to="pinax_lms_activities.ActivityState"),
            preserve_default=False,
        ),
    ]
