# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-26 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_lms_activities', '0009_auto_20160207_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitystate',
            name='activity_key',
            field=models.CharField(max_length=300),
        ),
    ]
